import { H } from "../dist/src/FriendlyHelper.js";

console.log(H.info.VERSION);
console.log(H.guid.generate());
console.log(H.color.generateRandomHex());
console.log(H.color.generateRandomRgb());
console.log(H.color.generateRandomRgba());
console.log(H.color.generateRandomHsl());
console.log(H.color.generateRandomHsla());
console.log(H.color.determineTransparency(H.color.generateRandomHex()) + "%");
console.log(H.color.determineTransparency(H.color.rgbaToHex(H.color.generateRandomRgba())) + "%");
console.log(H.color.determineTransparency(H.color.hslToHex(H.color.generateRandomHsl())) + "%");
console.log(H.color.determineTransparency(H.color.hslaToHex(H.color.generateRandomHsla())) + "%");
console.log(H.color.determineTransparency(H.color.rgbToHex(H.color.generateRandomRgb())) + "%");
console.log(H.string.capitalise(H.random.generateString(10)));
console.log(H.string.decapitalise(H.random.generateString(10)));
console.log(H.string.toUppercase(H.random.generateString(10)));
console.log(H.string.toLowercase(H.random.generateString(10)));
console.log(H.random.generateText(H.random.generateNumber(10, 200)));
console.log(H.random.generateObject());
console.log(H.random.generateObjectArray(H.random.generateNumber(10, 40)));
console.log(H.random.generateObjectArrayByJsonTemplate(H.random.generateNumber(10, 40), '{"name": "test", "age": false, "id": "24c02e2e-9966-4d07-bc18-2d8626c41235"}'));
